name: Build
on:
  push:
    branches:
      - 'master'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
      - uses: actions/checkout@v3
        with:
          repository: it-ony/webtest
          path: webtest
      - name: Build webtest
        run: cd webtest && mvn --no-transfer-progress clean install && cd ..

      - name: Setup Chromedriver
        uses: nanasess/setup-chromedriver@v1

      - name: Prepare test server
        run: |
          npm run build:test

      - name: run tests
        working-directory: ./test/webtest
        env:
          BUILD: ${{ github.ref }}-${{ github.run_id }}
          API_TOKEN: ${{ secrets.API_TOKEN }}
        run: |
          mvn --no-transfer-progress clean verify -Dbrowser=chrome -DthreadCount=10 -Denvironment=headless
          

  build:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - run: |
          npm ci
          npm run build
          sed 's/dist\///g' frame.html > dist/frame.html
          rm -r dist/src
          rm dist/*.map
      - name: deploy
        uses: JamesIves/github-pages-deploy-action@v4.3.3
        with:
          branch: gh-pages
          folder: dist
